# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          JWTSECRETKEY: ${{secrets.JWTSECRETKEY}}
          APIKEY: ${{APIKEY}}
          APPID: ${{APPID}}
          AUTHDOMAIN: ${{AUTHDOMAIN}}
          AUTH_PROVIDER_X509_CERT_URL: ${{AUTH_PROVIDER_X509_CERT_URL}}
          AUTH_URI: ${{AUTH_URI}}
          CLIENT_EMAIL: ${{CLIENT_EMAIL}}
          CLIENT_ID: ${{CLIENT_ID}}
          CLIENT_X509_CERT_URL: ${{CLIENT_X509_CERT_URL}}
          DATABASEURL: ${{DATABASEURL}}
          MESSAGINGSENDERID: ${{MESSAGINGSENDERID}}
          PRIVATE_KEY: ${{PRIVATE_KEY}}
          PRIVATE_KEY_ID: ${{PRIVATE_KEY_ID}}
          PROJECTID: ${{PROJECTID}}
          STORAGEBUCKET: ${{STORAGEBUCKET}}
          TOKEN_URI: ${{TOKEN_URI}}
          TYPE: ${{TYPE}}
      - run: npm ci
